
@startuml user_activities

(*) --> "User opens the app"

if "User is Sign up" then
    -->[yes]"User Sing in"
    -->"Authenticating user"
    if "Authentication succesfull"
    -->[yes]"User Swipes"
    --> "Find potential matches"
    --> "Display matches"
    --> "User interacts with matches"
    --> "Send/Receive messages"
    --> "Chat management"
    --> (*)
        
    else
        -->[no] "Do the process again"
        --> "Authenticating user"

    endif        
   
   
else
    -->[no]"User Sing up"
    -->"Verifying email"
    if "Valid Email" then
        -->[yes]"Create a password"
        if "Valid pasword?" then
        -->"Account created"
        -->"User Sing in"
        
      else
      -->[no]"Show ErrorMessage"
      -->"Create a password"        
      endif
    else
        -->"Invalid Email"
        -->"User Sing up"
    endif
endif

@enduml
