@startuml CD_relation_classes
class User {
    - ID: int
    - name: String
    - age: int
    - gender: String
    - location: String
    - preferences: List<String>
    + update_profile()
    + delete_account()
}

class MatchManager {
    - matches: List<Match>

    + find_matches(user: User): List<Match>
    + create_match(user1: User, user2: User)
}

class MessageManager {
    + send_message(sender: User, recipient: User, message: String)
    + get_messages(user: User): List<Message>
}

class Authentication {
    + register_user()
    + login_user()
    + logout_user()
}

class Database {
    - users: Dic<String, User>

    + query()
}

class Administrator {
    - username: String
    - password: String
    - privileges

    + sing_in(username: String, password: String)
    + view_reports()
    + block_user(user: User)
    + unblock_user(user: User)
    + view_existing_users(): List<User>
}

class Profile {
    - photos: List<String>
    - description: String
    - interests: List<String>
}

class InteractionProfiles {
    - users: List<User>
    - matches: List<Tuple<User, User>>

    + show_suggested_profiles(user: User)
}

User *-- Profile : contains
User *-- InteractionProfiles : contains
User --> Database : depends

Administrator --|> Database : has access to
Administrator --> User : interacts with

Authentication *--  Database : uses

InteractionProfiles *-- MatchManager : contains
InteractionProfiles *-- MessageManager : contains
@enduml
